version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.39.0-jammy
    # Steps to the job
    steps:
      - checkout
      - run:
          name: Download dependency
          command: npm install && npm ci
      - run:
          name: Run tests
          command: npm run test
      - store_test_results:
          path: results.xml
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test